### ISSUE TITLE
chat: visual duplication of some chat messages

### ISSUE THREAD

**Issue by litmus-ritten** [tloncorp/landscape-apps#1430]
Since Landscape 1, I have noticed that some chat messages are temporarily visually duplicated on post. This only happens to my own messages, survives navigation to different contexts within Groups, but the duplicate message disappears on refresh. This affects both textual and graphical chat messages.

**Graphical example**

![urbit - landscape 1 duplicate message bug](https://user-images.githubusercontent.com/62781197/206976657-87f73c62-a72f-4e4a-80fa-60d0d24b9366.png)

**To Reproduce**
1. Chat in groups.
2. Observe that sometimes a message is duplicated on post.

**Expected behaviour**
Chat messages should only show up once per message.

**Additional context:**
- Ship type: planet
- Instance type: self-hosted with CLI
- OS/browser: Vivaldi on Linux

**Comment by arthyn** [comment]
Possibly fixed with #1803, but can't reliably repro

**Comment by litmus-ritten** [comment]
I'm still seeing this. Could reproducibility be a function of pier speed and/or network speed?

**Comment by arthyn** [comment]
that pr hasn't been deployed yet sorry
